version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: parser_user
      POSTGRES_PASSWORD: parser_pass
      POSTGRES_DB: parser_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: